import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { cn } from "@/lib/utils";
import  Sidebar  from "@/components/sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-secondary", inter.className)}>
        <div className="main">
          <div className="gradient"></div>
        </div>
        <main className="relative z-10">
          <Navbar  />
          <div className="hidden md:flex mt-16 max-w-48 flex-col fixed inset-y-0 ">
              <Sidebar/>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
